name: Deploy Admin App to Azure Static Web Apps

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/admin-app/**'
      - '.github/workflows/deploy-admin-app.yml'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Admin App
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ADMIN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/admin-app"
          api_location: ""
          output_location: "dist"
